name: Deploy Python Application

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kin4stat/typing_count_bot:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull kin4stat/typing_count_bot:latest
          docker run --restart=always --name typing_count -e "TG_API_HASH=${{ secrets.TG_API_HASH }}" -e "TG_API_ID=${{ secrets.TG_API_ID }}" -v typing_count_volume:/persistent -p 127.0.0.1:25424:25424 -d kin4stat/typing_count_bot:latest